[package]
name = "Enigma"
version = "0.1.0"
authors = ["Aegen <kyuzo101@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console = "0.9.1"
text_io = "0.1.7"